spring.application.name=product-service
server.port=8081
spring.cloud.config.enabled=true
spring.cache.type=redis
spring.cache.host=localhost
spring.cache.port=6379
spring.cache.redis.time-to-live=60000

spring.config.import=configserver:http://localhost:3333